name: L10n Linter
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check strings
        run: |
          python .github/scripts/webext_l10n.py --l10n . --ref en_US --exceptions .github/scripts/exceptions.json
